# Generated by Django 3.0.8 on 2020-08-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
                ('count', models.IntegerField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('happiness', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('fear', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.User')),
            ],
        ),
    ]
