# Generated by Django 3.0.8 on 2020-08-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.User')),
            ],
        ),
    ]
